AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless CRUD Webservice to access a DynamoDB resource.

Resources:
  GamesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: name
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  GameLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lib/
      Handler: games.lambda_handler
      Runtime: python3.6
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref GamesTable
      Events:
        ListGames:
          Type: Api
          Properties:
            Path: /game
            Method: get